"""Added nullable fields for number check

Revision ID: 78624cbbb3c8
Revises: b8aaa31a26e0
Create Date: 2026-06-09 14:09:44.750061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78624cbbb3c8'
down_revision: Union[str, Sequence[str], None] = 'b8aaa31a26e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('number_check', 'carrier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('number_check', 'type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('number_check', 'local_format',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('number_check', 'local_format',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('number_check', 'type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('number_check', 'carrier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
