"""adding NumerCheck model

Revision ID: b8aaa31a26e0
Revises: 07cc817fa084
Create Date: 2026-06-03 14:24:53.394880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8aaa31a26e0'
down_revision: Union[str, Sequence[str], None] = '07cc817fa084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number_check',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=30), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('carrier', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('local_format', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('number_check')
    # ### end Alembic commands ###
