"""Added created_at field for check model

Revision ID: d69fa16a10a9
Revises: 78624cbbb3c8
Create Date: 2026-06-10 10:48:17.058310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69fa16a10a9'
down_revision: Union[str, Sequence[str], None] = '78624cbbb3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('number_check', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('number_check', 'created_at')
    # ### end Alembic commands ###
